version: "3"
services:
  frontend:
    build: ./frontend/studio-ghibli
    ports:
      - "${FRONTEND_APPLICATION_PORT}:80" # Custom port for frontend
    env_file:
      - .env # Use the main .env file
    networks:
      - studio-ghibil-network

  gateway:
    build: ./backend/gateway
    ports:
      - "${GATEWAY_SERVICE_PORT}:8880" # Custom port for gateway
    depends_on:
      - mysql
    env_file:
      - .env # Use the main .env file
    networks:
      - studio-ghibil-network
    environment:
      - COURSE_SERVICE_END_POINT=courses # Use the service name as hostname for courses
      - COURSE_SERVICE_PORT=8884 # Assuming this is the port courses is running on

  courses:
    build: ./backend/courses
    ports:
      - "${COURSE_SERVICE_PORT}:8884" # Custom port for courses microservice
    depends_on:
      - mysql
    env_file:
      - .env # Use the main .env file
    networks:
      - studio-ghibil-network

  mysql:
    image: mysql:latest
    ports:
      - "${DB_EXPOSE_PORT}:3306" # Custom port for MySQL
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}" # Custom root password
      MYSQL_DATABASE: "${DB_NAME}" # Custom database name
    volumes:
      - ./backend/sql/database.sql:/docker-entrypoint-initdb.d/init.sql # Mount the SQL script into the container
    env_file:
      - .env # Use the main .env file
    networks:
      - studio-ghibil-network
networks:
  studio-ghibil-network:
    driver: bridge
