version: "3"
services:
  frontend:
    build: ./frontend/studio-ghibli
    ports:
      - "9990:80"
    env_file: .env
    networks:
      - studio-ghibil-network

  admin_frontend:
    build: ./admin_frontend
    ports:
      - "9991:80"
    env_file: .env
    networks:
      - studio-ghibil-network

  gateway:
    build: ./backend/gateway
    ports:
      - "8880:8880"
    depends_on:
      - mysql
    env_file: .env
    networks:
      - studio-ghibil-network

  users:
    build: ./backend/users
    ports:
      - "8881:8881"
    depends_on:
      - mysql
    env_file: .env
    networks:
      - studio-ghibil-network

  customers:
    build: ./backend/customers
    ports:
      - "8882:8882"
    depends_on:
      - mysql
    env_file: .env
    networks:
      - studio-ghibil-network

  enrollment:
    build: ./backend/enrollment
    ports:
      - "8883:8883"
    depends_on:
      - mysql
    env_file: .env
    networks:
      - studio-ghibil-network

  courses:
    build: ./backend/courses
    ports:
      - "8884:8884"
    depends_on:
      - mysql
    env_file: .env
    networks:
      - studio-ghibil-network

  mysql:
    image: mysql:latest
    ports:
      - "${DB_EXPOSE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "sg@group1"
    volumes:
      - ./backend/sql/database.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
    networks:
      - studio-ghibil-network

networks:
  studio-ghibil-network:
    driver: bridge
