version: "3.8"

services:
  admin_frontend:
    build:
      context: ./admin_frontend
      dockerfile: Dockerfiles/Dockerfile.Dev
    ports:
      - "8886:80"
    networks:
      - sgproject

  public_frontend:
    build:
      context: ./frontend/studio-ghibli
      dockerfile: Dockerfiles/Dockerfile.Dev
    ports:
      - "8885:80"
    networks:
      - sgproject

  courses_backend:
    build:
      context: ./backend/courses
      dockerfile: Dockerfiles/Dockerfile.Dev
    ports:
      - "8884:8884"
    networks:
      - sgproject

  gateway_backend:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfiles/Dockerfile.Dev
    ports:
      - "8880:8880"
    networks:
      - sgproject

  customers_backend:
    build:
      context: ./backend/customers
      dockerfile: Dockerfiles/Dockerfile.Dev
    ports:
      - "8882:8882"
    networks:
      - sgproject

  users_backend:
    build:
      context: ./backend/users
      dockerfile: Dockerfiles/Dockerfile.Dev
    ports:
      - "8881:8881"
    networks:
      - sgproject

  enrollment_backend:
    build:
      context: ./backend/enrollment
      dockerfile: Dockerfiles/Dockerfile.Dev
    ports:
      - "8883:8883"
    networks:
      - sgproject

  sql_backend:
    build:
      context: ./backend/sql
      dockerfile: Dockerfiles/Dockerfile.Dev
    environment:
      MYSQL_ROOT_PASSWORD: sg@group1
      MYSQL_DATABASE: studio_ghibli_edu
      MYSQL_USER: sguser
      MYSQL_PASSWORD: sg@group1
    networks:
      - sgproject

networks:
  sgproject:
    driver: bridge
